### ISSUE TITLE
LOC112 LED (pins 1 and 2) is drawn backward

### ISSUE THREAD

**Issue by READ10** [PatrickBaus/KiCad-libraries#1]
Per the datasheet at:

http://www.ixysic.com/home/pdfs.nsf/www/LOC112.pdf/$file/LOC112.pdf

The LED anode is pin 2 and the cathode is pin 1.

**Comment by PatrickBaus** [comment]
Thank you very much for the input. I have swapped the pins in the schematic. The orientation of the diode is still the same to be consistent with existing optocouplers in KiCAD.
